# Generated by Django 2.1.5 on 2019-03-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190220_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('second', models.CharField(max_length=30)),
                ('target', models.CharField(max_length=30)),
                ('correct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Problem')),
            ],
        ),
    ]
